name: ROS2 humble image build 
on:
  workflow_dispatch:
  schedule:
    - cron: '55 13 * * *'
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cuda_ver: [nocuda, 12.4.1, 12.5.1, 12.6.3, 12.8.1, 12.9.1]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Docker Hub (nocuda)
        if: matrix.cuda_ver == 'nocuda'
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ros2_humble
          build-args: BASE_IMAGE=ubuntu:22.04
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ros2:humble
            ghcr.io/${{ github.repository_owner }}/ros2:humble

      - name: Build and Push to Docker Hub
        if: matrix.cuda_ver != 'nocuda'
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ros2_humble
          build-args: BASE_IMAGE=nvidia/cuda:${{ matrix.cuda_ver }}-cudnn-devel-ubuntu22.04
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ros2:humble_cuda${{ matrix.cuda_ver }}
            ghcr.io/${{ github.repository_owner }}/ros2:humble_cuda${{ matrix.cuda_ver }}
